### ISSUE TITLE
Is this repo under active maintenance?

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/puppet-nfs#189]
@derdanne Are you still working on this module?
@bastelfreak should this be migrated to voxpupuli?

**Comment by bastelfreak** [comment]
If someone want's to maintain it in Vox Pupuli and @derdanne wants to migrate it that's fine.

**Comment by derdanne** [comment]
Hey! Sorry to all of you!

Unfortunately, I do not work with Puppet in my current day job, so I can't reserve some time there on maintenance tasks on this module. Also it did not come to that point, where I could spend some free time to work on this module in the last year.

I see a lot of contributions, but I do not find the time to properly review the changes. I know how frustrating it could be, when there is no answer from repo owners. Therefore I would be happy, if this module could be migrated to Vox Pupuli and gets some more maintenance in the future, as it seems it is still used by some people.

@tuxmea @bastelfreak 
I would love to support the migration, how can I support you with this?

Kind regards,
Daniel

**Comment by bastelfreak** [comment]
@derdanne I send you an invitation to join the vox pupuli github org. afterwards you can migrate the repo. Of course you will keep write access to it. If you've other maintainers here let me know and I  will add them as well. The migration process is documented at https://voxpupuli.org/docs/migrate_module/

**Comment by derdanne** [comment]
Hey, thank you! The repository is transferred and you can complete the migration steps.

**Comment by tuxmea** [comment]
Migration completed. Closing.
